# Generated by Django 5.2.14 on 2026-06-01 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField(help_text='IndexedDB ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ward_box', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('calculator_type', models.CharField(max_length=100)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('inputs', models.JSONField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
                ('audit', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('user', 'local_id')},
            },
        ),
    ]
